name: Tests

on:
  push:
    branches: [ "master", "actions" ]
  pull_request:
    branches: [ "master", "actions" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
